# Docker compose

services:
  # Service Redis utilisé pour le stockage en cache
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    networks:
      - network-redis

  # Service PostgreSQL utilisé pour la base de données
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - network-postgres

  # Service utilisateur personnalisé
  user:
    build:
      context: .
    ports:
      - "8888:8888"
    networks:
      - network-user

  # Service de vote
  vote:
    build:
      context: ./vote
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - network-redis

  # Worker service qui dépend de Redis et PostgreSQL
  worker:
    build:
      context: ./worker
    depends_on:
      - postgres
      - redis
    networks:
      - network-redis
      - network-postgres

  # Service de résultat qui dépend du worker
  result:
    build:
      context: ./result
    ports:
      - "8081:8888"
    depends_on:
      - worker
    networks:
      - network-postgres

volumes:
  redis-volume:
    # Volume pour stocker les données Redis
  postgres-volume:
    # Volume pour stocker les données PostgreSQL

networks:
  network-user:
    # Réseau personnalisé pour le service utilisateur
  network-redis:
    # Réseau personnalisé pour les services Redis et Vote
  network-postgres:
    # Réseau personnalisé pour les services PostgreSQL, Worker, et Result
