services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    networks:
      - network-redis

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - network-postgres

  user:
    build:
      context: .
    ports:
      - "8888:8888"
    networks:
      - network-user

  vote:
    build:
      context: ./vote
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - network-redis

  worker:
    build:
      context: ./worker
    depends_on:
      - postgres
      - redis
    networks:
      - network-redis
      - network-postgres

  result:
    build:
      context: ./result
    ports:
      - "8081:8888"
    depends_on:
      - worker
    networks:
      - network-postgres

volumes:
  redis-volume:
  postgres-volume:

networks:
  network-user:
  network-redis:
  network-postgres:
