services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    networks:
      - network-1

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - network-1

  user:
    build:
      context: .
    ports:
      - "8888:8888"

  vote:
    build:
      context: ./vote
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - network-1

  worker:
    build:
      context: ./worker
    depends_on:
      - postgres
      - redis
    networks:
      - network-1

  result:
    build:
      context: ./result
    ports:
      - "8081:8888"
    depends_on:
      - worker
    networks:
      - network-1

volumes:
  redis-volume:
  postgres-volume:

networks:
  network-1:
